name: Docker Build and Push  CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Docker login  
      env:
        DOCKER_USER: edwincaro10
        DOCKER_PASSWORD: 1Dv1vvdu!
      run: docker login -u DOCKER_USER -p DOCKER_PASSWORD 
       
    - name: Build the Docker image   
      run: docker build . --file Dockerfile --tag edwincaro10/python-fastapi:myfastapi
      
    - name: Docker Push  
      run: docker push edwincaro10/python-fastapi:myfastapi   
