name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
#    - name: Build the Docker image   
#      run: docker build . --file Dockerfile --tag edwincaro10/python-fastapi:myfastapi
#    Docker  Push
    - name: Docker login
      env:
        DOCKER_USERS: ${{ secrets.DOCKER_USER }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}  
      run: docker login -u DOCKER_USER --password-stdin DOCKER_PASSWORD   
#    - name: Docker Push  
#      run: docker push edwincaro10/python-fastapi:myfastapi   
